services:
  redis:
    image: redis:7
    # container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./server
    # container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    # container_name: frontend
    ports:
      - "5173:5173" # Vite dev server
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

# Note to run in dev mode without Docker
# cd server ; npm run start (with docker installed)
# cd client ; npm run dev